DEEPSORT:
  # 预训练reid模型参数文件
  REID_CKPT: "./deepsort/deep/checkpoint/ckpt1.t7"
  # 最大余弦距离
  MAX_DIST: 0.2
  # 确认检测结果最小置信度
  MIN_CONFIDENCE: 0.3
  # NMS最大IOU
  NMS_MAX_OVERLAP: 0.5
  # IOU匹配时最大IOU距离
  MAX_IOU_DISTANCE: 0.7
  # 最大生命周期
  MAX_AGE: 50
  # 确认轨迹所需帧数
  N_INIT: 3
  # 临时特征向量容量，课减少保证运行速度
  NN_BUDGET: 100
  